language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: landl_ww@163.com
branches:
  only:
    - master
    - dev
node_js:
  - '8'
script:
  - npm run test:prod && npm run build
after_success:
  - |
    cat ./coverage/lcov.info | ./node_modules/.bin/codecov