language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: landl_ww@163.com
node_js:
  - '8'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  except:
    - /^v\d+\.\d+\.\d+$/
